stages:
  - build-ai-bsp

variables:
  BUILD_DIR: ${CI_PROJECT_DIR}/build
  OUTPUT_DIR: ${CI_PROJECT_DIR}/output
  PROP_LIBS_DIR: ${CI_PROJECT_DIR}/prop_libs

.selective_rules: &selective_rules
  rules:
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH && $CI_COMMIT_BRANCH
      when: manual
      allow_failure: true
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH || $CI_COMMIT_TAG
      when: always

.rzg2:
  image: gitlab.renesas.solutions:5050/spl2/continuous-integration/dockerfiles:ubuntu-18.04-latest
  variables:
    PROP_LIBS_BRANCH: rzg2_v1.0.10_prod

.rzg2l:
  image: gitlab.renesas.solutions:5050/spl2/continuous-integration/dockerfiles:ubuntu-20.04-latest
  variables:
    PROP_LIBS_BRANCH: rzg2l_v1.4_prod

.hihope-rzg2h:
  extends: [".rzg2"]
  variables:
    PLATFORM: hihope-rzg2h

.hihope-rzg2m:
  extends: [".rzg2"]
  variables:
    PLATFORM: hihope-rzg2m

.hihope-rzg2n:
  extends: [".rzg2"]
  variables:
    PLATFORM: hihope-rzg2n

.ek874:
  extends: [".rzg2"]
  variables:
    PLATFORM: ek874

.smarc-rzg2l:
  extends: [".rzg2l"]
  variables:
    PLATFORM: smarc-rzg2l

.smarc-rzg2lc:
  extends: [".rzg2l"]
  variables:
    PLATFORM: smarc-rzg2lc

.smarc-rzg2ul:
  extends: [".rzg2l"]
  variables:
    PLATFORM: smarc-rzg2ul

.build-meta-renesas-ai:
  tags:
    - yocto
  before_script:
    - printenv
    - rm -rf ${OUTPUT_DIR} ${PROP_LIBS_DIR} ${BUILD_DIR}
  script:
    - mkdir -p ${OUTPUT_DIR} ${PROP_LIBS_DIR} ${BUILD_DIR}
    - git clone git@gitlab.renesas.solutions:spl2/continuous-integration/proprietary-libs.git ${PROP_LIBS_DIR}
    - pushd ${PROP_LIBS_DIR} && git checkout ${PROP_LIBS_BRANCH} && popd
    - pushd ${BUILD_DIR}
    - ${CI_PROJECT_DIR}/scripts/build-rzg-ai-bsp.sh -p ${PLATFORM} -l ${PROP_LIBS_DIR} -f ${FRAMEWORK} -o ${OUTPUT_DIR} -e -s ${EXTRA_BUILD_ARGS}
  artifacts:
    name: "${CI_JOB_NAME}"
    when: always
    expire_in: 1 month
    paths:
      - ${BUILD_DIR}/build/conf/bblayers.conf
      - ${BUILD_DIR}/build/conf/local.conf
      - ${OUTPUT_DIR}/


benchmark:armnn:hihope-rzg2h:
  stage: build-ai-bsp
  extends: [".build-meta-renesas-ai", ".hihope-rzg2h"]
  variables:
    FRAMEWORK: armnn
    EXTRA_BUILD_ARGS: "-b"
  <<: *selective_rules

benchmark:ort:hihope-rzg2h:
  stage: build-ai-bsp
  extends: [".build-meta-renesas-ai", ".hihope-rzg2h"]
  variables:
    FRAMEWORK: onnxruntime
    EXTRA_BUILD_ARGS: "-b"
  <<: *selective_rules

benchmark:tflite:hihope-rzg2h:
  stage: build-ai-bsp
  extends: [".build-meta-renesas-ai", ".hihope-rzg2h"]
  variables:
    FRAMEWORK: tensorflow-lite
    EXTRA_BUILD_ARGS: "-b"
  <<: *selective_rules

benchmark:armnn:hihope-rzg2m:
  stage: build-ai-bsp
  extends: [".build-meta-renesas-ai", ".hihope-rzg2m"]
  variables:
    FRAMEWORK: armnn
    EXTRA_BUILD_ARGS: "-b"

benchmark:ort:hihope-rzg2m:
  stage: build-ai-bsp
  extends: [".build-meta-renesas-ai", ".hihope-rzg2m"]
  variables:
    FRAMEWORK: onnxruntime
    EXTRA_BUILD_ARGS: "-b"

benchmark:tflite:hihope-rzg2m:
  stage: build-ai-bsp
  extends: [".build-meta-renesas-ai", ".hihope-rzg2m"]
  variables:
    FRAMEWORK: tensorflow-lite
    EXTRA_BUILD_ARGS: "-b"

benchmark:armnn:hihope-rzg2n:
  stage: build-ai-bsp
  extends: [".build-meta-renesas-ai", ".hihope-rzg2n"]
  variables:
    FRAMEWORK: armnn
    EXTRA_BUILD_ARGS: "-b"
  <<: *selective_rules

benchmark:ort:hihope-rzg2n:
  stage: build-ai-bsp
  extends: [".build-meta-renesas-ai", ".hihope-rzg2n"]
  variables:
    FRAMEWORK: onnxruntime
    EXTRA_BUILD_ARGS: "-b"
  <<: *selective_rules

benchmark:tflite:hihope-rzg2n:
  stage: build-ai-bsp
  extends: [".build-meta-renesas-ai", ".hihope-rzg2n"]
  variables:
    FRAMEWORK: tensorflow-lite
    EXTRA_BUILD_ARGS: "-b"
  <<: *selective_rules

benchmark:armnn:ek874:
  stage: build-ai-bsp
  extends: [".build-meta-renesas-ai", ".ek874"]
  variables:
    FRAMEWORK: armnn
    EXTRA_BUILD_ARGS: "-b"
  <<: *selective_rules

benchmark:ort:ek874:
  stage: build-ai-bsp
  extends: [".build-meta-renesas-ai", ".ek874"]
  variables:
    FRAMEWORK: onnxruntime
    EXTRA_BUILD_ARGS: "-b"
  <<: *selective_rules

benchmark:tflite:ek874:
  stage: build-ai-bsp
  extends: [".build-meta-renesas-ai", ".ek874"]
  variables:
    FRAMEWORK: tensorflow-lite
    EXTRA_BUILD_ARGS: "-b"
  <<: *selective_rules

benchmark:armnn:smarc-rzg2l:
  stage: build-ai-bsp
  extends: [".build-meta-renesas-ai", ".smarc-rzg2l"]
  variables:
    FRAMEWORK: armnn
    EXTRA_BUILD_ARGS: "-b"

benchmark:ort:smarc-rzg2l:
  stage: build-ai-bsp
  extends: [".build-meta-renesas-ai", ".smarc-rzg2l"]
  variables:
    FRAMEWORK: onnxruntime
    EXTRA_BUILD_ARGS: "-b"

benchmark:tflite:smarc-rzg2l:
  stage: build-ai-bsp
  extends: [".build-meta-renesas-ai", ".smarc-rzg2l"]
  variables:
    FRAMEWORK: tensorflow-lite
    EXTRA_BUILD_ARGS: "-b"

benchmark:armnn:smarc-rzg2lc:
  stage: build-ai-bsp
  extends: [".build-meta-renesas-ai", ".smarc-rzg2lc"]
  variables:
    FRAMEWORK: armnn
    EXTRA_BUILD_ARGS: "-b"
  <<: *selective_rules

benchmark:ort:smarc-rzg2lc:
  stage: build-ai-bsp
  extends: [".build-meta-renesas-ai", ".smarc-rzg2lc"]
  variables:
    FRAMEWORK: onnxruntime
    EXTRA_BUILD_ARGS: "-b"
  <<: *selective_rules

benchmark:tflite:smarc-rzg2lc:
  stage: build-ai-bsp
  extends: [".build-meta-renesas-ai", ".smarc-rzg2lc"]
  variables:
    FRAMEWORK: tensorflow-lite
    EXTRA_BUILD_ARGS: "-b"
  <<: *selective_rules

benchmark:armnn:smarc-rzg2ul:
  stage: build-ai-bsp
  extends: [".build-meta-renesas-ai", ".smarc-rzg2ul"]
  variables:
    FRAMEWORK: armnn
    EXTRA_BUILD_ARGS: "-b"
  <<: *selective_rules

benchmark:ort:smarc-rzg2ul:
  stage: build-ai-bsp
  extends: [".build-meta-renesas-ai", ".smarc-rzg2ul"]
  variables:
    FRAMEWORK: onnxruntime
    EXTRA_BUILD_ARGS: "-b"
  <<: *selective_rules

benchmark:tflite:smarc-rzg2ul:
  stage: build-ai-bsp
  extends: [".build-meta-renesas-ai", ".smarc-rzg2ul"]
  variables:
    FRAMEWORK: tensorflow-lite
    EXTRA_BUILD_ARGS: "-b"
  <<: *selective_rules

