stages:
  - build

variables:
  CI_META_RENESAS_AI_REF: ${CI_COMMIT_REF_NAME}
  CI_RZG2_BSP_TAG: v1.0.10-update1
  CI_RZG2L_BSP_TAG: v1.4
  YOCTO_DL_DIR: ${CI_PROJECT_DIR}/downloads
  YOCTO_SSTATE_DIR: ${CI_PROJECT_DIR}/sstate_cache

.rzg2-test:
  variables:
    CI_GRAPHICS_LICENSE: prod
    CI_META_RENESAS_AI_CONFIGURATION: templates/rzg2
    CI_META_RENESAS_MANIFEST: meta-cip-tests__dev.xml
    CI_BASE_MANIFEST: bsp-rzg2__${CI_RZG2_BSP_TAG}.xml
    BUILD_SCRIPT: build-manifest__rzg2__meta-renesas-ai__gitlab-ci-test.sh

.rzg2l-test:
  variables:
    CI_GRAPHICS_LICENSE: prod
    CI_META_RENESAS_AI_CONFIGURATION: templates/rzg2l
    CI_META_RENESAS_MANIFEST: meta-cip-tests__dev.xml
    CI_BASE_MANIFEST: bsp-rzg2l__${CI_RZG2L_BSP_TAG}.xml
    BUILD_SCRIPT: build-manifest__rzg2l__meta-renesas-ai__gitlab-ci-test.sh

.rzg2-release:
  variables:
    CI_GRAPHICS_LICENSE: eval
    CI_META_RENESAS_AI_CONFIGURATION: templates/rzg2
    CI_META_RENESAS_MANIFEST: bsp-rzg2__${CI_RZG2_BSP_TAG}.xml
    BUILD_SCRIPT: build-manifest__rzg2__meta-renesas-ai__gitlab-ci-release.sh

.rzg2l-release:
  variables:
    CI_GRAPHICS_LICENSE: eval
    CI_META_RENESAS_AI_CONFIGURATION: templates/rzg2l
    CI_META_RENESAS_MANIFEST: bsp-rzg2l__${CI_RZG2L_BSP_TAG}.xml
    BUILD_SCRIPT: build-manifest__rzg2l__meta-renesas-ai__gitlab-ci-release.sh

.ek874:
  variables:
    CI_GRAPHICS_MACHINE: rzg2e-prod
    CI_MACHINE: ek874

.hihope-rzg2n:
  variables:
    CI_GRAPHICS_MACHINE: rzg2n-prod
    CI_MACHINE: hihope-rzg2n

.hihope-rzg2m:
  variables:
    CI_GRAPHICS_MACHINE: rzg2m-prod
    CI_MACHINE: hihope-rzg2m

.hihope-rzg2h:
  variables:
    CI_GRAPHICS_MACHINE: rzg2h-prod
    CI_MACHINE: hihope-rzg2h

.smarc-rzg2ul:
  variables:
    CI_MACHINE: smarc-rzg2ul

.smarc-rzg2lc:
  variables:
    CI_MACHINE: smarc-rzg2lc

.smarc-rzg2l:
  variables:
    CI_MACHINE: smarc-rzg2l

.build_meta-renesas-ai:
  stage: build
  tags:
    - yocto
  variables:
    GIT_STRATEGY: none
  before_script:
    - if [ ${CI_COMMIT_TAG} ]; then CI_META_RENESAS_AI_REF=refs/tags/${CI_COMMIT_REF_NAME}; fi
    - rm -rf build-scripts; rm -f job_list.csv
    - git clone git@gitlab.renesas.solutions:spl2/continuous-integration/build-scripts.git
    - cd build-scripts
    - PATH=$PATH:$(pwd)
    - git checkout "${CI_BUILD_SCRIPTS_REF:-$CI_COMMIT_REF_NAME}" && export CI_BUILD_SCRIPTS_REF=$CI_COMMIT_REF_NAME || true
  cache:
    - key: "downloads"
      paths:
        - ${YOCTO_DL_DIR}
    - key: "sstate-cache-${CI_MACHINE}"
      paths:
        - ${YOCTO_SSTATE_DIR}
  artifacts:
    name: "${CI_JOB_NAME}-${CI_JOB_ID}"
    when: always
    expire_in: 1 month
    paths:
      - build-scripts/url_list.csv
      - job_list.csv
      - build-scripts/build/build/conf/bblayers.conf
      - build-scripts/build/build/conf/local.conf

.rzg2_meta-renesas-ai_test:
  image: gitlab.renesas.solutions:5050/spl2/continuous-integration/dockerfiles:ubuntu-18.04-latest
  extends: [.build_meta-renesas-ai, .rzg2-test]
  script:
    - ci-yocto-build.sh -s ${BUILD_SCRIPT} -p $(pwd)/build-scripts -D ${YOCTO_DL_DIR}
    - cd ..
    - 'submit-lava-job.sh -E ${GITLAB_USER_EMAIL} -m "gitlab.pipeline-url: ${CI_PIPELINE_URL}" -m "gitlab.job-url: ${CI_JOB_URL}" -f build-scripts/url_list.csv'
    - cat job_list.csv || true

.rzg2_meta-renesas-ai_release:
  image: gitlab.renesas.solutions:5050/spl2/continuous-integration/dockerfiles:ubuntu-18.04-latest
  extends: [.build_meta-renesas-ai, .rzg2-release]
  script:
    - ci-yocto-build.sh -s ${BUILD_SCRIPT} -p $(pwd)/build-scripts -D ${YOCTO_DL_DIR}

.rzg2l_meta-renesas-ai_test:
  image: gitlab.renesas.solutions:5050/spl2/continuous-integration/dockerfiles:ubuntu-20.04-latest
  extends: [.build_meta-renesas-ai, .rzg2l-test]
  script:
    - ci-yocto-build.sh -s ${BUILD_SCRIPT} -p $(pwd)/build-scripts -D ${YOCTO_DL_DIR}
    - cd ..
    - 'submit-lava-job.sh -E ${GITLAB_USER_EMAIL} -m "gitlab.pipeline-url: ${CI_PIPELINE_URL}" -m "gitlab.job-url: ${CI_JOB_URL}" -f build-scripts/url_list.csv'
    - cat job_list.csv || true

.rzg2l_meta-renesas-ai_release:
  image: gitlab.renesas.solutions:5050/spl2/continuous-integration/dockerfiles:ubuntu-20.04-latest
  extends: [.build_meta-renesas-ai, .rzg2l-release]
  script:
    - ci-yocto-build.sh -s ${BUILD_SCRIPT} -p $(pwd)/build-scripts -D ${YOCTO_DL_DIR}

################################################################################
# Build and test
################################################################################
.build-and-test_rules-manual: &build-and-test_rules-manual
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      when: always
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_MERGE_REQUEST_IID
      when: never
    - when: manual
      allow_failure: true

.build-and-test_rules-auto: &build-and-test_rules-auto
    - if: $CI_COMMIT_BRANCH
      when: always
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_MERGE_REQUEST_IID
      when: never

# armnn+tfl
armnn_ek874_build-and-test:
  extends: [.rzg2_meta-renesas-ai_test, .ek874]
  variables:
    CI_CONF_NAME: armnn
  rules: *build-and-test_rules-manual

armnn_hihope-rzg2n_build-and-test:
  extends: [.rzg2_meta-renesas-ai_test, .hihope-rzg2n]
  variables:
    CI_CONF_NAME: armnn
  rules: *build-and-test_rules-manual

armnn_hihope-rzg2m_build-and-test:
  extends: [.rzg2_meta-renesas-ai_test, .hihope-rzg2m]
  variables:
    CI_CONF_NAME: armnn
  rules: *build-and-test_rules-auto

armnn_hihope-rzg2h_build-and-test:
  extends: [.rzg2_meta-renesas-ai_test, .hihope-rzg2h]
  variables:
    CI_CONF_NAME: armnn
  rules: *build-and-test_rules-manual

armnn_smarc-rzg2l_build-and-test:
  extends: [.rzg2l_meta-renesas-ai_test, .smarc-rzg2l]
  variables:
    CI_CONF_NAME: armnn
  rules: *build-and-test_rules-auto

armnn_smarc-rzg2lc_build-and-test:
  extends: [.rzg2l_meta-renesas-ai_test, .smarc-rzg2lc]
  variables:
    CI_CONF_NAME: armnn
  rules: *build-and-test_rules-manual

armnn_smarc-rzg2ul_build-and-test:
  extends: [.rzg2l_meta-renesas-ai_test, .smarc-rzg2ul]
  variables:
    CI_CONF_NAME: armnn
  rules: *build-and-test_rules-manual

# onnx
onnx_ek874_build-and-test:
  extends: [.rzg2_meta-renesas-ai_test, .ek874]
  variables:
    CI_CONF_NAME: onnxruntime
  rules: *build-and-test_rules-manual

onnx_hihope-rzg2n_build-and-test:
  extends: [.rzg2_meta-renesas-ai_test, .hihope-rzg2n]
  variables:
    CI_CONF_NAME: onnxruntime
  rules: *build-and-test_rules-manual

onnx_hihope-rzg2m_build-and-test:
  extends: [.rzg2_meta-renesas-ai_test, .hihope-rzg2m]
  variables:
    CI_CONF_NAME: onnxruntime
  rules: *build-and-test_rules-auto

onnx_hihope-rzg2h_build-and-test:
  extends: [.rzg2_meta-renesas-ai_test, .hihope-rzg2h]
  variables:
    CI_CONF_NAME: onnxruntime
  rules: *build-and-test_rules-manual

onnx_smarc-rzg2l_build-and-test:
  variables:
  extends: [.rzg2l_meta-renesas-ai_test, .smarc-rzg2l]
  variables:
    CI_CONF_NAME: onnxruntime
  rules: *build-and-test_rules-auto

onnx_smarc-rzg2lc_build-and-test:
  variables:
  extends: [.rzg2l_meta-renesas-ai_test, .smarc-rzg2lc]
  variables:
    CI_CONF_NAME: onnxruntime
  rules: *build-and-test_rules-manual

onnx_smarc-rzg2ul_build-and-test:
  variables:
  extends: [.rzg2l_meta-renesas-ai_test, .smarc-rzg2ul]
  variables:
    CI_CONF_NAME: onnxruntime
  rules: *build-and-test_rules-manual

# tflite
tfl_ek874_build-and-test:
  extends: [.rzg2_meta-renesas-ai_test, .ek874]
  variables:
    CI_CONF_NAME: tensorflow-lite
  rules: *build-and-test_rules-manual

tfl_hihope-rzg2n_build-and-test:
  extends: [.rzg2_meta-renesas-ai_test, .hihope-rzg2n]
  variables:
    CI_CONF_NAME: tensorflow-lite
  rules: *build-and-test_rules-manual

tfl_hihope-rzg2m_build-and-test:
  extends: [.rzg2_meta-renesas-ai_test, .hihope-rzg2m]
  variables:
    CI_CONF_NAME: tensorflow-lite
  rules: *build-and-test_rules-auto

tfl_hihope-rzg2h_build-and-test:
  extends: [.rzg2_meta-renesas-ai_test, .hihope-rzg2h]
  variables:
    CI_CONF_NAME: tensorflow-lite
  rules: *build-and-test_rules-manual

tfl_smarc-rzg2l_build-and-test:
  extends: [.rzg2l_meta-renesas-ai_test, .smarc-rzg2l]
  variables:
    CI_CONF_NAME: tensorflow-lite
  rules: *build-and-test_rules-auto

tfl_smarc-rzg2lc_build-and-test:
  extends: [.rzg2l_meta-renesas-ai_test, .smarc-rzg2lc]
  variables:
    CI_CONF_NAME: tensorflow-lite
  rules: *build-and-test_rules-manual

tfl_smarc-rzg2ul_build-and-test:
  extends: [.rzg2l_meta-renesas-ai_test, .smarc-rzg2ul]
  variables:
    CI_CONF_NAME: tensorflow-lite
  rules: *build-and-test_rules-manual

################################################################################
# Build only (i.e. don't include meta-cip-tests)
################################################################################
.build-only_rules: &build-only_rules
    - if: $CI_COMMIT_TAG
      when: always

# armnn
armnn_ek874_build-only:
  extends: [.rzg2_meta-renesas-ai_release, .ek874]
  variables:
    CI_CONF_NAME: armnn
  rules: *build-only_rules

armnn_hihope-rzg2n_build-only:
  extends: [.rzg2_meta-renesas-ai_release, .hihope-rzg2n]
  variables:
    CI_CONF_NAME: armnn
  rules: *build-only_rules

armnn_hihope-rzg2m_build-only:
  extends: [.rzg2_meta-renesas-ai_release, .hihope-rzg2m]
  variables:
    CI_CONF_NAME: armnn
  rules: *build-only_rules

armnn_hihope-rzg2h_build-only:
  extends: [.rzg2_meta-renesas-ai_release, .hihope-rzg2h]
  variables:
    CI_CONF_NAME: armnn
  rules: *build-only_rules

armnn_smarc-rzg2l_build-only:
  extends: [.rzg2l_meta-renesas-ai_release, .smarc-rzg2l]
  variables:
    CI_CONF_NAME: armnn
  rules: *build-only_rules

armnn_smarc-rzg2lc_build-only:
  extends: [.rzg2l_meta-renesas-ai_release, .smarc-rzg2lc]
  variables:
    CI_CONF_NAME: armnn
  rules: *build-only_rules

armnn_smarc-rzg2ul_build-only:
  extends: [.rzg2l_meta-renesas-ai_release, .smarc-rzg2ul]
  variables:
    CI_CONF_NAME: armnn
  rules: *build-only_rules

# onnxruntime
onnxruntime_ek874_build-only:
  extends: [.rzg2_meta-renesas-ai_release, .ek874]
  variables:
    CI_CONF_NAME: onnxruntime
  rules: *build-only_rules

onnxruntime_hihope-rzg2n_build-only:
  extends: [.rzg2_meta-renesas-ai_release, .hihope-rzg2n]
  variables:
    CI_CONF_NAME: onnxruntime
  rules: *build-only_rules

onnxruntime_hihope-rzg2m_build-only:
  extends: [.rzg2_meta-renesas-ai_release, .hihope-rzg2m]
  variables:
    CI_CONF_NAME: onnxruntime
  rules: *build-only_rules

onnxruntime_hihope-rzg2h_build-only:
  extends: [.rzg2_meta-renesas-ai_release, .hihope-rzg2h]
  variables:
    CI_CONF_NAME: onnxruntime
  rules: *build-only_rules

onnxruntime_smarc-rzg2l_build-only:
  extends: [.rzg2l_meta-renesas-ai_release, .smarc-rzg2l]
  variables:
    CI_CONF_NAME: onnxruntime
  rules: *build-only_rules

onnxruntime_smarc-rzg2lc_build-only:
  extends: [.rzg2l_meta-renesas-ai_release, .smarc-rzg2lc]
  variables:
    CI_CONF_NAME: onnxruntime
  rules: *build-only_rules

onnxruntime_smarc-rzg2ul_build-only:
  extends: [.rzg2l_meta-renesas-ai_release, .smarc-rzg2ul]
  variables:
    CI_CONF_NAME: onnxruntime
  rules: *build-only_rules

# tensorflow-lite
tensorflow-lite_ek874_build-only:
  extends: [.rzg2_meta-renesas-ai_release, .ek874]
  variables:
    CI_CONF_NAME: tensorflow-lite
  rules: *build-only_rules

tensorflow-lite_hihope-rzg2n_build-only:
  extends: [.rzg2_meta-renesas-ai_release, .hihope-rzg2n]
  variables:
    CI_CONF_NAME: tensorflow-lite
  rules: *build-only_rules

tensorflow-lite_hihope-rzg2m_build-only:
  extends: [.rzg2_meta-renesas-ai_release, .hihope-rzg2m]
  variables:
    CI_CONF_NAME: tensorflow-lite
  rules: *build-only_rules

tensorflow-lite_hihope-rzg2h_build-only:
  extends: [.rzg2_meta-renesas-ai_release, .hihope-rzg2h]
  variables:
    CI_CONF_NAME: tensorflow-lite
  rules: *build-only_rules

tensorflow-lite_smarc-rzg2l_build-only:
  extends: [.rzg2l_meta-renesas-ai_release, .smarc-rzg2l]
  variables:
    CI_CONF_NAME: tensorflow-lite
  rules: *build-only_rules

tensorflow-lite_smarc-rzg2lc_build-only:
  extends: [.rzg2l_meta-renesas-ai_release, .smarc-rzg2lc]
  variables:
    CI_CONF_NAME: tensorflow-lite
  rules: *build-only_rules

tensorflow-lite_smarc-rzg2ul_build-only:
  extends: [.rzg2l_meta-renesas-ai_release, .smarc-rzg2ul]
  variables:
    CI_CONF_NAME: tensorflow-lite
  rules: *build-only_rules
